version: "2"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - './mongo:/data/db'
    expose: 
      - "27017"

  node:
    image: "node:latest"
    user: "node"
    restart: always
    depends_on:
      - db
    working_dir: /home/node/app
    volumes:
      - ./src:/home/node/app
    expose:
      - "8081:3000"
    command: "npm run prod"