version: "2"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - './mongo:/data/db'
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    expose: 
      - "27017"

  wachanmeldung:
    image: "node:latest"
    user: "root"
    restart: always
    depends_on:
      - db
    working_dir: /home/node/app
    volumes:
      - ./src:/home/node/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    expose:
      - "3000"
    command: "npm run prod"